train:
    algorithm:
        name: PPO
        class_name: PPO

        # PPO 超参数
        clip_param: 0.2
        desired_kl: 0.01
        entropy_coef: 0.01
        gamma: 0.99
        lam: 0.95
        learning_rate: 0.001
        max_grad_norm: 1.0
        num_learning_epochs: 5
        num_mini_batches: 4
        schedule: "adaptive"
        use_clipped_value_loss: true
        value_loss_coef: 1.0

    runner:
        policy_class_name: "ActorCritic"
        algorithm_class_name: "PPO"
        checkpoint: -1
        max_iterations: 1500
        save_interval: 50
        experiment_name: "g1_dance_test"
